# Generated by Django 5.2.1 on 2025-06-02 16:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='chats/'),
        ),
    ]
