# Generated by Django 5.2.1 on 2025-06-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_admins_alter_chat_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='groups',
            field=models.BooleanField(default=False),
        ),
    ]
