# Generated by Django 5.2.1 on 2025-06-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='from_community',
            field=models.BooleanField(default=False),
        ),
    ]
